services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MongoDB\Database:
        alias: 'mongo.connection'

    League\Fractal\Manager:
        class: League\Fractal\Manager

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Command\:
        resource: '../src/Command'
        tags: ['console.command']

    App\Repository\ChannelRepositoryInterface:
        class: App\Repository\ChannelRepository

    App\Repository\VideoRepositoryInterface:
        class: App\Repository\VideoRepository

    App\Repository\StatsRepositoryInterface:
        class: App\Repository\StatsRepository

    App\Repository\YoutubeRepositoryInterface:
        class: App\Repository\YoutubeApiRepository